# Note than an .asf.yaml file is also needed
# in the asf-site branch that's used for the
# live website. See https://infra-reports.apache.org/site-source/
github:
  description: "Apache Sling Website"
  homepage: "https://sling.apache.org/"
  labels:
    - sling
    - website
    - jbake
publish:
  whoami: asf-site
